name: Troubleshooting Limits Security Checks

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  show-repo-runners:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Install gh
        uses: actions/setup-gh@v1

      - name: List self-hosted runners
        run: |
          gh api repos/${{ github.repository }}/actions/runners --jq <<'EOF'
          .runners[] | {name, status, busy, os, labels: [ .labels[].name ]}
          EOF
          echo
          echo "If a job is 'Waiting for a runner to pick up this job...', your runner is offline, has mismatched labels/group, or is not reachable."

      - name: Show recent workflow runs + conclusions
        run: |
          gh api repos/${{ github.repository }}/actions/runs --jq <<'EOF' | head -n 20
          .workflow_runs[] | {name, status, conclusion, event, run_number} | .
          EOF

      - name: Print known platform limits (FYI only)
        run: |
          cat <<'LIMITS'
          • Workflow runtime limit: ~35 days (then canceled)
          • Job queue time: ~24h (if not started → terminated)
          • API requests: ~1000/hour across all actions in a repo (then fail)
          • Matrix max jobs: 256 per workflow run
          • Workflow run queue: ~500 per 10s interval per repo (excess fails to complete)
          • Queue by Actions: ~within 30 minutes of trigger if services up
          LIMITS

      - name: Reminder - security guidance for self-hosted
        run: |
          cat <<'SEC'
          • Avoid public repos: PRs from forks can run arbitrary code on your machine.
          • Treat the box as untrusted between jobs unless you reset it (ephemeral runners help).
          • Control network egress/ingress (VPN/VPC/IP allow list/proxy).
          • The runner process is a normal user (not root); use sudo as needed.
          SEC

  runner-connectivity-check:
    # This job runs on self-hosted runners to demonstrate connectivity
    runs-on: [ self-hosted ]
    timeout-minutes: 5
    steps:
      - name: Show runner information
        run: |
          echo "This job is running on a self-hosted runner:"
          echo "Runner name: $RUNNER_NAME"
          echo "Runner OS: $RUNNER_OS"
          echo "Runner architecture: $RUNNER_ARCH"
          echo "Runner workspace: $RUNNER_WORKSPACE"
          echo "Runner temp: $RUNNER_TEMP"
      
      - name: Test GitHub connectivity (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          Write-Host "Testing connectivity to GitHub..."
          try {
            $response = Invoke-WebRequest -Uri "https://api.github.com" -UseBasicParsing
            Write-Host " - GitHub API is reachable (HTTP $($response.StatusCode))"
          } catch {
            Write-Host " - GitHub API is not reachable: $($_.Exception.Message)"
          }

      - name: Test GitHub connectivity (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          echo "Testing connectivity to GitHub..."
          curl -s -o /dev/null -w "%{http_code}" https://api.github.com
          echo " - GitHub API is reachable"
