name: 02 - Labels & Runner Groups (matrix)

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  # A) Use the "object" form to target a runner GROUP + labels.here
  use-runner-group:
    # Requires your runner to be in group "scan-runners"
    runs-on:
      group: scan-runners
      labels: [ self-hosted, linux ]  # add "ssd" etc. if you gave those labels
    steps:
      - run: |
          echo "Runner name: $RUNNER_NAME"
          echo "OS: $RUNNER_OS | Arch: $RUNNER_ARCH | Temp: $RUNNER_TEMP"

  # B) Matrix across labels (architecture, disk)
  matrix-by-labels:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        labelset:
          - [ self-hosted, linux, x64 ]
          - [ self-hosted, linux, arm64 ]
          # Add custom labels you assigned during registration:
          # - [ self-hosted, linux, ssd ]
    runs-on: ${{ matrix.labelset }}
    steps:
      - run: |
          echo "Labels used: ${{ join(matrix.labelset, ', ') }}"
          echo "Runner labels available: $RUNNER_LABELS"
