name: Troubleshooting Limits Security Checks

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  show-repo-runners:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Install gh
        uses: cli/cli-action@v2

      - name: List self-hosted runners (status: online/offline)
        run: |
          gh api repos/${{ github.repository }}/actions/runners --jq '.runners[] | {name, status, busy, os, labels: [ .labels[].name ]}'
          echo
          echo "If a job is 'Waiting for a runner to pick up this job...', your runner is offline, has mismatched labels/group, or is not reachable."

      - name: Show recent workflow runs + conclusions
        run: |
          gh api repos/${{ github.repository }}/actions/runs --jq '.workflow_runs[] | {name, status, conclusion, event, run_number} | . ' | head -n 20

      - name: Print known platform limits (FYI only)
        run: |
          cat <<'LIMITS'
          • Workflow runtime limit: ~35 days (then canceled)
          • Job queue time: ~24h (if not started → terminated)
          • API requests: ~1000/hour across all actions in a repo (then fail)
          • Matrix max jobs: 256 per workflow run
          • Workflow run queue: ~500 per 10s interval per repo (excess fails to complete)
          • Queue by Actions: ~within 30 minutes of trigger if services up
          LIMITS

      - name: Reminder - security guidance for self-hosted
        run: |
          cat <<'SEC'
          • Avoid public repos: PRs from forks can run arbitrary code on your machine.
          • Treat the box as untrusted between jobs unless you reset it (ephemeral runners help).
          • Control network egress/ingress (VPN/VPC/IP allow list/proxy).
          • The runner process is a normal user (not root); use sudo as needed.
          SEC

  runner-connectivity-check:
    # Optional PAT with "workflow" scope to run local runner diagnostics
    if: ${{ secrets.RUNNER_PAT != '' }}
    runs-on: self-hosted
    steps:
      - name: Explain what will happen
        run: |
          echo "This job demonstrates the idea from the page:"
          echo "On your runner box, you can run: ./run.sh --check --url https://github.com/${{ github.repository }} --pat ****"
          echo "We just show the command here; execute it on the runner if you want full diagnostics."
          echo "./run.sh --check --url https://github.com/${{ github.repository }} --pat <PAT_WITH_WORKFLOW_SCOPE>"
