name: 02 — Tokens & fine-grained permissions

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Start strict. Individual jobs will request only what they need.
permissions: 
  contents: read

jobs:
  list-issues-readonly:
    name: Read with GITHUB_TOKEN (read-only)
    runs-on: ubuntu-latest
    steps:
      - name: Show token source options
        run: |
          echo "secrets.GITHUB_TOKEN is auto-created per run."
          echo "github.token is the same token via the github context."
      - name: List first 3 issues via REST using github.token
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
        run: |
          curl -s -H "authorization: Bearer $GH_TOKEN"             -H "accept: application/vnd.github+json"             https://api.github.com/repos/$REPO/issues?per_page=3 | jq '.[].title' || true

  create-issue-on-failure:
    name: Create an issue only when allowed (opt-up permissions)
    runs-on: ubuntu-latest
    # Escalate permissions JUST for this job
    permissions:
      contents: read
      issues: write
    steps:
      - name: Simulate a failure (but continue to run so we can create an issue)
        id: maybe_fail
        run: |
          echo "Pretending something failed..."; exit 0

      - name: Create issue via REST API
        if: always()
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
        run: |
          TITLE="Automated notice from workflow"
          BODY="This demonstrates using per-job permissions with the GITHUB_TOKEN."
          curl -s -X POST -H "authorization: Bearer $GH_TOKEN"             -H "accept: application/vnd.github+json"             https://api.github.com/repos/$REPO/issues             -d "$(jq -n --arg t "$TITLE" --arg b "$BODY" '{title:$t, body:$b}')"             | jq '.html_url' || true

  deny-all-demo:
    name: Deny-all permissions (expected to fail harmlessly)
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions: {}
    steps:
      - name: Try to call API without permissions (should fail)
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
        run: |
          set -e
          echo "This request should fail due to {} permissions."
          curl -f -s -H "authorization: Bearer xxx"             https://api.github.com/repos/$REPO || true

  use-pat-secret:
    name: Call API with PAT stored as secret
    runs-on: ubuntu-latest
    steps:
      - name: POST with PAT (minimal scopes) — do NOT hardcode tokens
        env:
          PAT: ${{ secrets.WORKFLOW_PAT }}
          REPO: ${{ github.repository }}
        run: |
          curl -s -H "authorization: Bearer $PAT"                -H "accept: application/vnd.github+json"                https://api.github.com/repos/$REPO | jq '.full_name' || true
