name: 03 — PR safety (pull_request vs pull_request_target)

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]
  pull_request_target:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]

# Default to read-only
permissions: {
 contents: read
}

jobs:
  pr_build_readonly:
    name: Build & test with read-only token (safe default)
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Example build step (replace with real build)
        run: |
          echo "Running build for PR #${{ github.event.pull_request.number }}"
          echo "Token is read-only because event is pull_request from fork."

  pr_target_no_checkout:
    name: Target-context automation WITHOUT checking out PR HEAD
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Add a label safely via REST (no checkout of untrusted code)
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
          PR: ${{ github.event.pull_request.number }}
        run: |
          curl -s -X POST -H "authorization: Bearer $GH_TOKEN"               
           -H "accept: application/vnd.github+json"                https://api.github.com/repos/$REPO/issues/$PR/labels                -d '{"labels":["needs-review"]}' | jq '.labels | length' || true

      # DO NOT do this here (example only):
      # - uses: actions/checkout@v4
      #   with:
      #     ref: ${{ github.event.pull_request.head.sha }}
      # ^ Checking out PR HEAD in a target-context job exposes secrets & write perms to untrusted code.
