name: "Ultimate Mastery CI/CD"

on:
  push:
    branches: ["main", "hello"]  # Fixed: Added space
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      run-tests:
        description: "Run unit tests?"
        type: boolean
        default: true
      timeout-minutes:
        description: "Timeout in minutes"
        type: number
        default: 10
      deploy-env:
        description: "Deploy environment"
        required: true
        type: choice
        default: 'staging'
        options:
          - staging
          - production
          - development
  repository_dispatch:
    types: [external-build]
  schedule:
    - cron: "30 5,15 * * *"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    outputs:
      build-time: ${{ steps.build-time.outputs.build-time }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      
      - name: Build with Maven
        run: mvn -B -ntp -DskipTests package
      
      - name: Run tests with Maven
        if: ${{ inputs.run-tests || github.event_name != 'workflow_dispatch' }}  # Fixed: Added space
        run: mvn -B -ntp test
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'build-artifact'
          path: 'target/*.jar'
      
      - name: Set build time output
        id: build-time
        run: echo "build-time=$(date -u +%FT%TZ)" >> $GITHUB_OUTPUT  # Fixed: ISO format

  hello-job:
    runs-on: ubuntu-latest
    outputs:
      greeting: ${{ steps.hello.outputs.greeting }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Say hello from ${{ runner.os }}
        uses: ./.github/actions/say-hello
        id: hello
        with:
          who: "Linux-${{ runner.os }}"

  consume-outputs:
    runs-on: ubuntu-latest
    needs: [hello-job, build-linux]  # Fixed: Added space
    steps:
      - name: Echo greeting
        run: |
          echo "Greeting from build-time was: '${{ needs.build-linux.outputs.build-time }}'"  # Fixed: Added quote
          echo "Greeting from hello-job was: '${{ needs.hello-job.outputs.greeting }}'"  # Fixed: Added quote

  external-trigger:
    if: github.event_name == 'repository_dispatch' && github.event.action == 'external-build'
    runs-on: ubuntu-latest
    steps:
      - name: Dump external payload
        run: echo '${{ toJson(github.event.client_payload) }}'

  deploy:
    runs-on: ubuntu-latest
    needs: [build-linux]
    steps:
      - name: Deploy to staging
        if: inputs.deploy-env == 'staging'
        run: echo "Deploying to ${{ inputs.deploy-env }}"
      
      - name: Deploy to production
        if: inputs.deploy-env == 'production'
        run: echo "Deploying to production with key ${{ inputs.deploy-env }}"

  build-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B -ntp -DskipTests package

      - name: Java Version Print
        run: java -version

      - name: Display OS info
        run: |
          echo "OS: ${{ matrix.os }}"
          echo "Runner OS: ${{ runner.os }}"
      
      - name: Generate artifacts
        run: | 
          echo "report" > report.txt
          echo "Build Completed" >> report.txt
          echo "Runner OS: ${{ runner.os }}" >> report.txt
          echo "Matrix OS: ${{ matrix.os }}" >> report.txt

      - name: Upload matrix report
        uses: actions/upload-artifact@v4
        with:
          name: 'matrix-report-${{ runner.os }}'
          path: 'report.txt'