name: Deployments example

on:
  push:
    branches: ["main", "dev"]

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      # Change from Gradle to Maven
      - name: Build
        run: mvn clean package -DskipTests

      - name: Test
        run: mvn test

      # Change path from Gradle to Maven heresds
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jars
          path: target/*.jar

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    needs: [build-and-test]
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://github.com/${{ github.repository }}/releases/tag/v${{ vars.DEV_VERSION }}

    steps:
      - name: Download candidate artifacts
        uses: actions/download-artifact@v4
        with:
          name: app-jars
          path: dist

      - name: GH Release (dev)
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: v${{ vars.DEV_VERSION }}
          name: dev
          draft: true
          prerelease: true
          files: dist/*.jar
       

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    needs: [build-and-test]
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://github.com/${{ github.repository }}/releases/tag/v${{ vars.PROD_VERSION }}

    steps:
      - name: Download candidate artifacts
        uses: actions/download-artifact@v4
        with:
          name: app-jars
          path: dist

      - name: GH Release (prod)
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: v${{ vars.PROD_VERSION }}
          name: Production
          generate_release_notes: true
          files: dist/*.jar
          #token: ${{ secrets.PROD_TOKEN }}