name: After Pipeline Completes

on:
  workflow_run:
    workflows: ["Pipeline"]           # must match the *name:* of the upstream workflow
    types: [completed]
    branches: ["rel/**", "!rel/**-preprod"]  # include + exclude using negation

permissions:
  contents: read
  issues: write                         # needed to create issues

jobs:
  echo-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Show triggering workflow info
        run: |
          echo "Name:        ${{ github.event.workflow_run.name }}"
          echo "Conclusion:  ${{ github.event.workflow_run.conclusion }}"
          echo "Head branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Run ID:      ${{ github.event.workflow_run.id }}"

  create-issue-on-failure:
    # Only run if upstream is not success
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    uses: ./.github/workflows/create-failure-issue.yml
    with:
      title: "Follow-up: Pipeline ${{ github.event.workflow_run.conclusion }} on ${{ github.event.workflow_run.head_branch }}"
      body:  "See run ID: ${{ github.event.workflow_run.id }}"
    secrets: inherit
