name: After Pipeline Completes

on:
  # Debug trigger for testing - remove this once it works
  workflow_dispatch:
    inputs:
      debug_message:
        description: 'Debug message for manual testing'
        required: false
        default: 'Testing workflow manually'

  workflow_run:
    workflows: ["Runners demo"]           # must match the *name:* of the upstream workflow
    types: [completed]
    branches: ["main","rel/**", "!rel/**-preprod"]  # include + exclude using negation

permissions:
  contents: read
  issues: write                         # needed to create issues

jobs:
  debug-info:
    runs-on: ubuntu-latest
    if: always()  # Always run regardless of trigger
    steps:
      - name: GitHub Event Details (DEBUG)
        run: |
          echo "=== GITHUB EVENT DEBUG ==="
          echo "Event Name:        ${{ github.event_name }}"
          echo "Workflow:          ${{ github.workflow }}"
          echo "Run ID:            ${{ github.run_id }}"
          echo "Server URL:        ${{ github.server_url }}"
          echo "Repository:        ${{ github.repository }}"
          echo "Ref:               ${{ github.ref }}"
          echo "Head Ref:          ${{ github.head_ref }}"
          echo "Base Ref:          ${{ github.base_ref }}"
          echo "Event JSON (limited):" 
          echo "${{ toJSON(github.event) }}" | head -20
          echo "======================="

  echo-upstream:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_run' }}  # Only run when triggered by workflow_run
    steps:
      - name: Show triggering workflow info
        run: |
          echo "=== WORKFLOW RUN TRIGGER DEBUG ==="
          echo "Triggered by workflow name: '${{ github.event.workflow_run.name }}'"
          echo "Expected workflow name:     'Runners demo'"
          echo "Exact name match status:     '${{ github.event.workflow_run.name == 'Runners demo' }}'"
          echo "Conclusion:                 '${{ github.event.workflow_run.conclusion }}'"
          echo "Head branch:               '${{ github.event.workflow_run.head_branch }}'"
          echo "Run ID:                     '${{ github.event.workflow_run.id }}'"
          echo "Current branch pattern matching:"
          echo "  - main:                   included"
          echo "  - rel/** pattern:         included" 
          echo "  - rel/**-preprod:         excluded"
          echo "Source workflow branch for comparison: '${{ github.event.workflow_run.head_branch }}'"
          echo "==================================="

  create-issue-on-failure:
    # Only run if upstream is not success
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    uses: ./.github/workflows/create-failure-issue.yml
    with:
      title: "Follow-up: Pipeline ${{ github.event.workflow_run.conclusion }} on ${{ github.event.workflow_run.head_branch }}"
      body:  "See run ID: ${{ github.event.workflow_run.id }}"
    secrets: inherit
