name: After Pipeline Completes

on:
  workflow_run:
    workflows: ["Pipeline"]
    types: [completed]
    branches: ['rel/**', '!rel/**-preprod']  # Include rel/** but exclude preprod branches

jobs:
  react:
    runs-on: ubuntu-latest
    steps:
      - name: Show conclusion from triggering workflow
        run: echo "Upstream conclusion ${{ github.event.workflow_run.conclusion }}"

  create-issue-if-failed:
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    uses: ./.github/workflows/create-failure-issue.yml
    with:
      title: "Follow-up: Pipeline ${{ github.event.workflow_run.conclusion }} on ${{ github.event.workflow_run.head_branch }}"
      body:  "See run ID: ${{ github.event.workflow_run.id }}"
    secrets: inherit
