name: 02 — Reusable Inputs/Outputs

on:
  workflow_call:
    inputs:
      message:
        description: "A message from the caller"
        required: true
        type: string
    secrets:
      token:
        required: false
    outputs:                               # reusable workflow can expose outputs to caller
      echoed:
        description: "The echoed message"
        value: ${{ jobs.echo.outputs.out }}

  # Also allow manual dispatch to see the same behavior from the UI
  workflow_dispatch:
    inputs:
      message:
        description: "Message to echo"
        required: true
        type: string

jobs:
  echo:
    runs-on: ubuntu-latest
    outputs:
      out: ${{ steps.out.outputs.value }}
    steps:
      - name: Echo input (step output)
        id: out
        shell: bash
        run: |
          echo "value=You said: ${{ inputs.message }}" >> "$GITHUB_OUTPUT"
