name: "Reusable CI (Maven build + artifact)"

on:
  workflow_call:
    inputs:
      java-version:
        description: "Java version (e.g., 21, 17)"
        required: true
        type: string
      artifact-name:
        description: "Name for build artifact"
        required: false
        default: "app-jar"
        type: string
      run-tests:
        description: "Run unit tests?"
        required: false
        default: true
        type: boolean
    secrets:
      token:
        description: "Optional PAT for private registries"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Pull repo
      - name: Checkout source
        uses: actions/checkout@v4

      # Install Temurin JDK + enable Maven dependency caching
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java-version }}
          cache: 'maven'

      # Build
      - name: Build (no tests yet)
        run: mvn -B -ntp -DskipTests package

      # Tests (optional via input)
      - name: Run unit tests
        if: ${{ inputs.run-tests }}
        run: mvn -B -ntp test

      # Create a fat JAR (already configured via shade plugin)
      - name: Package shaded JAR
        run: mvn -B -ntp -DskipTests package

      # Upload artifacts (JAR + any reports/)
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: |
            target/*-with-dependencies.jar
            reports/
