name: Token examples

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  issues: write   # raised on the page as an example of augmenting permissions

jobs:
  label-and-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Example A: pass the workflow token to an action that needs it
      - name: Auto-label PR
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # Example B: make a REST call with the token (read-only GET shown here)
      - name: Call GitHub REST API with token
        run: |
          curl -sSfL \
            -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }} \
            | head -n 20
