name: Runners demo (ubuntu/macos/windows)

on:
  # Git events with qualifiers (branches / tags / paths)
  push:
    branches: [ "main", "rel/*" ,"hello"]       # Only default + release branches
    tags:     [ "v*" ]                   # Version-like tags e.g., v1.0.0
    paths:    [ "**.java", "pom.xml" ]   # Only when Java source or pom changes
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # run this one manually from the Actions tab

permissions:
  contents: read

jobs:
  matrix-info:
    # Demonstrates "ubuntu-latest", "macos-latest", "windows-latest" labels
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Print basic runner info
        run: |
          echo "Runner OS: $RUNNER_OS"
          echo "Runner Temp: $RUNNER_TEMP"
          echo "Default shell varies by OS (bash on Linux/macOS, PowerShell on Windows)."

      - name: Show kernel / system details (Linux & macOS)
        if: runner.os != 'Windows'
        run: |
          uname -a
          sw_vers || true  # prints macOS version when available

      - name: Show system details (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "System info:"
          systeminfo | findstr /B /C:"OS Name" /C:"OS Version"

      # Chapter 5: "Adding Additional Software on Runners" example (Linux)
      - name: Install an extra package on ubuntu-latest
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y tree
          tree -L 1 .

      - name: Guidance to Included Software list (read the job log)
        run: |
          echo "In the job log, expand 'Set up job' → 'Runner Image' → 'Included Software' to see preinstalled tools."
          echo "SBOMs for runner images are available on the actions/runner-images releases page (as described in the book)."
